//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dungeons_and_Dragons_Player_Maker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Backgrounds {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Backgrounds() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dungeons_and_Dragons_Player_Maker.Backgrounds", typeof(Backgrounds).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criminal Contact: You have a reliable and trustworthy contact who acts as your liaison to a network of other criminals. You know how to get messages to and from your contact, even over great distances; specifically, you know the local messengers, corrupt caravan masters, and seedy sailors who can deliver messages for you..
        /// </summary>
        internal static string Criminal_Spy {
            get {
                return ResourceManager.GetString("Criminal/Spy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I’m trying to pay off an old debt I owe to a generous benefactor._My ill-gotten gains go to support my family._Something important was taken from me, and I aim to steal it back._I will become the greatest thief that ever lived._I’m guilty of a terrible crime. I hope I can redeem myself for it._Someone I loved died because of a mistake I made. That will never happen again..
        /// </summary>
        internal static string Criminal_Spy_Bond {
            get {
                return ResourceManager.GetString("Criminal/Spy-Bond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When I see something valuable, I can’t think about anything but how to steal it._When faced with a choice between money and my friends, I usually choose the money._If there’s a plan, I’ll forget it. If I don’t forget it, I’ll ignore it._I have a “tell” that reveals when I’m lying._I turn tail and run when things look bad._An innocent person is in prison for a crime that I committed. I’m okay with that..
        /// </summary>
        internal static string Criminal_Spy_Flaw {
            get {
                return ResourceManager.GetString("Criminal/Spy-Flaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don’t steal from others in the trade._Chains are meant to be broken, as are those who would forge them._I steal from the wealthy so that I can help people in need._I will do whatever it takes to become wealthy._I’m loyal to my friends, not to any ideals, and everyone else can take a trip down the Styx for all I care._There’s a spark of good in everyone..
        /// </summary>
        internal static string Criminal_Spy_Ideal {
            get {
                return ResourceManager.GetString("Criminal/Spy-Ideal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A crowbar, a set of dark common clothes, a pouch containing 15 gp..
        /// </summary>
        internal static string Criminal_Spy_Items {
            get {
                return ResourceManager.GetString("Criminal/Spy-Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I always have a plan for what to do when things go wrong._I am always calm, no matter what the situation. I never raise my voice or let my emotions control me._The first thing I do in a new place is note the locations of everything valuable—or where such things could be hidden._I would rather make a new friend than a new enemy._I am incredibly slow to trust. Those who seem the fairest often have the most to hide._I don’t pay attention to the risks in a situation. Never tell me the odds._The best way to get  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Criminal_Spy_Personality {
            get {
                return ResourceManager.GetString("Criminal/Spy-Personality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages: None_Skills: Deception, Stealth_Tools: Thieves&apos; Tools, &lt;CHOOSE&gt;.
        /// </summary>
        internal static string Criminal_Spy_Skills {
            get {
                return ResourceManager.GetString("Criminal/Spy-Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City Secrets: You know the secret patterns and flow to cities and can find passages through the urban sprawl that others would miss. When you are not in combat, you (and companions you lead) can travel between any two locations in the city twice as fast as your speed would normally allow..
        /// </summary>
        internal static string Urchin {
            get {
                return ResourceManager.GetString("Urchin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My town or city is my home, and I&apos;ll fight to defend it._I sponsor an orphanage to keep others from enduring what I was forced to endure._I owe my survival to another urchin who taught me to live on the streets._I owe a debt I can never repay to the person who took pity on me._I escaped my life of poverty by robbing an important person, and I&apos;m wanted for it._No one else should have to endure the hardships I&apos;ve been through..
        /// </summary>
        internal static string Urchin_Bond {
            get {
                return ResourceManager.GetString("Urchin-Bond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If I&apos;m outnumbered, I will run away from a fight._Gold seems like a lot of money to me, and I&apos;ll do just about anything for more of it._I will never fully trust anyone other than myself._I&apos;d rather kill someone in their sleep than fight fair_It&apos;s not stealing if I need it more than someone else._People who can&apos;t take care of themselves get what they deserve..
        /// </summary>
        internal static string Urchin_Flaw {
            get {
                return ResourceManager.GetString("Urchin-Flaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All people, rich or poor, deserve respect._We have to take care of each other, because no one else is going to do it._The low are lifted up, and the high and mighty are brought down. Change is the nature of things._The rich need to be shown what life and death are like in the gutters._I help the people who help me-that&apos;s what keeps us alive._I&apos;m going to prove that I&apos;m worthy of a better life..
        /// </summary>
        internal static string Urchin_Ideal {
            get {
                return ResourceManager.GetString("Urchin-Ideal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A small knife, a map of the city, a pet mouse, a token, a set of common clothes, a pouch containing 10 gp..
        /// </summary>
        internal static string Urchin_Items {
            get {
                return ResourceManager.GetString("Urchin-Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I hide scraps of food and trinkets away in my pockets._I ask a lot of questions._I like to squeeze into small places where no one else can get to me._I sleep with my back to a wall or tree, with everything I own wrapped in a bundle in my arms._I eat like a pig and have bad manners._I think anyone who&apos;s nice to me is hiding evil intent._I don&apos;t like to bathe._I bluntly say what other people are hinting at or hiding..
        /// </summary>
        internal static string Urchin_Personality {
            get {
                return ResourceManager.GetString("Urchin-Personality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages: None_Skills: Sleight of Hand, Stealth_Tools: Disguise kit, thieves&apos; tools.
        /// </summary>
        internal static string Urchin_Skills {
            get {
                return ResourceManager.GetString("Urchin-Skills", resourceCulture);
            }
        }
    }
}
