//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dungeons_and_Dragons_Player_Maker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Classes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Classes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dungeons_and_Dragons_Player_Maker.Classes", typeof(Classes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Artificer {
            get {
                object obj = ResourceManager.GetObject("Artificer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Barbarian {
            get {
                object obj = ResourceManager.GetObject("Barbarian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rage - 1, 9, 15_Unarmored Defense - 1_Reckless Attack, Danger Sense - 2_Extra Attack, Fast Movement - 5_Feral Instinct - 7_Brutal Critical - 9_Indomitable Might - 18_Primal Champion - 20.
        /// </summary>
        internal static string Barbarian_Base {
            get {
                return ResourceManager.GetString("Barbarian:Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frenzy - 3_Mindless Rage - 6_Intimidating Presence - 10_Retaliation - 14.
        /// </summary>
        internal static string Barbarian_Berserker {
            get {
                return ResourceManager.GetString("Barbarian:Berserker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explorer&apos;s Pack_Javelin x4.
        /// </summary>
        internal static string Barbarian_Items {
            get {
                return ResourceManager.GetString("Barbarian:Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Armor_Medium Armor_Shields_Simple Weapons_Martial Weapons.
        /// </summary>
        internal static string Barbarian_Skills {
            get {
                return ResourceManager.GetString("Barbarian:Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirit Seeker, Totem Spirit - 3_Aspect of the Beast - 6_Spirit Walker - 10_Totem Attunement - 14.
        /// </summary>
        internal static string Barbarian_Totem_Warrior {
            get {
                return ResourceManager.GetString("Barbarian:Totem Warrior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bard {
            get {
                object obj = ResourceManager.GetObject("Bard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bardic Insperation - 1, 20_Jack of All Trades - 2_Expertise - 3_Font of Inspiration - 5_Countercharm - 6_Magical Secrets - 10.
        /// </summary>
        internal static string Bard_Base {
            get {
                return ResourceManager.GetString("Bard:Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leather Armor_Dagger.
        /// </summary>
        internal static string Bard_Items {
            get {
                return ResourceManager.GetString("Bard:Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Proficiencies - 3_Cutting Words - 3_Additional Magical Secrets - 6_Peerless Skill - 14.
        /// </summary>
        internal static string Bard_Lore {
            get {
                return ResourceManager.GetString("Bard:Lore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple weapons_hand crossbow_longsword_rapier_shortsword.
        /// </summary>
        internal static string Bard_Skills {
            get {
                return ResourceManager.GetString("Bard:Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Proficiencies - 3_Combat Inspiration - 3_Extra Attack - 6_Battle Magic - 14.
        /// </summary>
        internal static string Bard_Valor {
            get {
                return ResourceManager.GetString("Bard:Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cleric {
            get {
                object obj = ResourceManager.GetObject("Cleric", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divine Domain - 1_Channel Divinity - 2, 6_Destroy Undead - 5_Divine Intervention - 10.
        /// </summary>
        internal static string Cleric_Base {
            get {
                return ResourceManager.GetString("Cleric:Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield_Holy Symbol.
        /// </summary>
        internal static string Cleric_Items {
            get {
                return ResourceManager.GetString("Cleric:Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blessings Of Knowledge - 1_Potent Spellcasting - 8_Visions of the Past - 17.
        /// </summary>
        internal static string Cleric_Knowledge {
            get {
                return ResourceManager.GetString("Cleric:Knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Proficiency, Disciple of Life - 1_Blessed Healer - 6_Divine Strike - 8_Supreme Healing - 17.
        /// </summary>
        internal static string Cleric_Life {
            get {
                return ResourceManager.GetString("Cleric:Life", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Cantrip, Warding Flare - 1_Improved Flare - 6_Potent Spellcasting - 8_Corona of Light - 17.
        /// </summary>
        internal static string Cleric_Light {
            get {
                return ResourceManager.GetString("Cleric:Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acolyte of Nature, Bonus Proficiency - 1_Dampen Elements - 6_Divine Strike - 8_Master of Nature - 17.
        /// </summary>
        internal static string Cleric_Nature {
            get {
                return ResourceManager.GetString("Cleric:Nature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Armor_Medium Armor_Shields_Simple Weapons.
        /// </summary>
        internal static string Cleric_Skills {
            get {
                return ResourceManager.GetString("Cleric:Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Proficiencies, Wrath of the Storm - 1_Thunderbolt Strike - 6_Divine Strike - 8_Stormborn - 17.
        /// </summary>
        internal static string Cleric_Tempest {
            get {
                return ResourceManager.GetString("Cleric:Tempest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blessing of the Trickster - 1_Divine Strike - 8_Improved Duplicity - 17.
        /// </summary>
        internal static string Cleric_Trickery {
            get {
                return ResourceManager.GetString("Cleric:Trickery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Proficiencies, War Priest - 1_Dvine Strike - 8_Avatar of Battle - 17.
        /// </summary>
        internal static string Cleric_War {
            get {
                return ResourceManager.GetString("Cleric:War", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Druid {
            get {
                object obj = ResourceManager.GetObject("Druid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Druidic - 1_Wild Shape - 2_Timeless Body - 18_Beast Spells - 18_Archdruid - 20.
        /// </summary>
        internal static string Druid_Base {
            get {
                return ResourceManager.GetString("Druid:Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Cantrip, Natural Recovery - 2_Land&apos;s Stride - 6_Nature&apos;s Ward - 10_Nature&apos;s Sanctuary - 14.
        /// </summary>
        internal static string Druid_Circle_of_the_Land {
            get {
                return ResourceManager.GetString("Druid:Circle of the Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat Wild Shape, Circle Forms - 2_Primal Strike - 6_Elemental Wild Shape - 10_Thousand Forms - 14.
        /// </summary>
        internal static string Druid_Circle_of_the_Moon {
            get {
                return ResourceManager.GetString("Druid:Circle of the Moon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leather Armor_Explorer&apos;s Pack_Druidic Focus.
        /// </summary>
        internal static string Druid_Items {
            get {
                return ResourceManager.GetString("Druid:Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Armor_Medium Armor_Shields_Clubs_Daggers_Darts_Javelins_Maces_Quarterstaffs_Scimitars_Sickles_Slings_Spears_Herbalism kit.
        /// </summary>
        internal static string Druid_Skills {
            get {
                return ResourceManager.GetString("Druid:Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Fighter {
            get {
                object obj = ResourceManager.GetObject("Fighter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monk {
            get {
                object obj = ResourceManager.GetObject("Monk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Paladin {
            get {
                object obj = ResourceManager.GetObject("Paladin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ranger {
            get {
                object obj = ResourceManager.GetObject("Ranger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rogue {
            get {
                object obj = ResourceManager.GetObject("Rogue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sorcerer {
            get {
                object obj = ResourceManager.GetObject("Sorcerer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Spell_Sheet {
            get {
                object obj = ResourceManager.GetObject("Spell Sheet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Warlock {
            get {
                object obj = ResourceManager.GetObject("Warlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wizard {
            get {
                object obj = ResourceManager.GetObject("Wizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
