//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dungeons_and_Dragons_Player_Maker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Races {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Races() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dungeons_and_Dragons_Player_Maker.Races", typeof(Races).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2_0_0_0_0_+1_30_Medium_Common, Draconic_None_Breath Weapon - Acid, Damage Resistance - Acid.
        /// </summary>
        internal static string Dragonborn_Black {
            get {
                return ResourceManager.GetString("Dragonborn:Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2_0_0_0_0_+1_30_Medium_Common, Draconic_None_Breath Weapon - Lightning, Damage Resistance - Lightning.
        /// </summary>
        internal static string Dragonborn_Blue {
            get {
                return ResourceManager.GetString("Dragonborn:Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2_0_0_0_0_+1_30_Medium_Common, Draconic_None_Breath Weapon - Fire, Damage Resistance - Fire.
        /// </summary>
        internal static string Dragonborn_Brass {
            get {
                return ResourceManager.GetString("Dragonborn:Brass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2_0_0_0_0_+1_30_Medium_Common, Draconic_None_Breath Weapon - Lightning, Damage Resistance - Lightning.
        /// </summary>
        internal static string Dragonborn_Bronze {
            get {
                return ResourceManager.GetString("Dragonborn:Bronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2_0_0_0_0_+1_30_Medium_Common, Draconic_None_Breath Weapon - Acid, Damage Resistance - Acid.
        /// </summary>
        internal static string Dragonborn_Copper {
            get {
                return ResourceManager.GetString("Dragonborn:Copper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2_0_0_0_0_+1_30_Medium_Common, Draconic_None_Breath Weapon - Fire, Damage Resistance - Fire.
        /// </summary>
        internal static string Dragonborn_Gold {
            get {
                return ResourceManager.GetString("Dragonborn:Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2_0_0_0_0_+1_30_Medium_Common, Draconic_None_Breath Weapon - Poison, Damage Resistance - Poison.
        /// </summary>
        internal static string Dragonborn_Green {
            get {
                return ResourceManager.GetString("Dragonborn:Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2_0_0_0_0_+1_30_Medium_Common, Draconic_None_Breath Weapon, Damage Resistance.
        /// </summary>
        internal static string Dragonborn_Natural {
            get {
                return ResourceManager.GetString("Dragonborn:Natural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2_0_0_0_0_+1_30_Medium_Common, Draconic_None_Breath Weapon - Fire, Damage Resistance - Fire.
        /// </summary>
        internal static string Dragonborn_Red {
            get {
                return ResourceManager.GetString("Dragonborn:Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2_0_0_0_0_+1_30_Medium_Common, Draconic_None_Breath Weapon - Cold, Damage Resistance - Cold.
        /// </summary>
        internal static string Dragonborn_Silver {
            get {
                return ResourceManager.GetString("Dragonborn:Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2_0_0_0_0_+1_30_Medium_Common, Draconic_None_Breath Weapon - Cold, Damage Resistance - Cold.
        /// </summary>
        internal static string Dragonborn_White {
            get {
                return ResourceManager.GetString("Dragonborn:White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0_0_+2_+1_0_0_25_Medium_Common, Dwarvish_Battleaxe, handaxe, light hammer, warhammer_Darkvision - 60ft, Dwarven Resilience, Stonecunning, Dwarven Toughness.
        /// </summary>
        internal static string Dwarf_Hill {
            get {
                return ResourceManager.GetString("Dwarf:Hill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2_0_+2_0_0_0_25_Medium_Common, Dwarvish_Battleaxe, handaxe, light hammer, warhammer, light armor, medium armor_Darkvision - 60ft, Dwarven Resilience, Stonecunning.
        /// </summary>
        internal static string Dwarf_Mountain {
            get {
                return ResourceManager.GetString("Dwarf:Mountain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0_0_+2_0_0_0_25_Medium_Common, Dwarvish_Battleaxe, handaxe, light hammer, warhammer_Darkvision - 60ft, Dwarven Resilience, Stonecunning.
        /// </summary>
        internal static string Dwarf_Natural {
            get {
                return ResourceManager.GetString("Dwarf:Natural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0_+2_0_0_0_+1_30_Medium_Common, Elvish_Perception, rapiers, shortswords, hand crossbows_Darkvision - 120ft, Fey Ancestry, Trance, Sunlight Sensitivity, Drow Magic.
        /// </summary>
        internal static string Elf_Drow {
            get {
                return ResourceManager.GetString("Elf:Drow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0_+2_0_0_+1_0_30_Medium_Common, Elvish_Perception, longsword, shortsword, shortbow, longbow_Darkvision - 60ft, Fey Ancestry, Trance, Cantrip.
        /// </summary>
        internal static string Elf_High {
            get {
                return ResourceManager.GetString("Elf:High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0_+2_0_0_0_0_30_Medium_Common, Elvish_Perception_Darkvision - 60ft, Fey Ancestry, Trance.
        /// </summary>
        internal static string Elf_Natural {
            get {
                return ResourceManager.GetString("Elf:Natural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0_+2_0_+1_0_0_35_Medium_Common, Elvish_Perception, longsword, shortsword, shortbow, longbow_Darkvision - 60ft, Fey Ancestry, Trance, Mask of the Wild.
        /// </summary>
        internal static string Elf_Wood {
            get {
                return ResourceManager.GetString("Elf:Wood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0_+1_0_0_+2_0_25_Small_Common, Gnomish_None_Darkvision - 60ft, Gnome Cunning, Natural Illusionist, Speak with Small Beasts.
        /// </summary>
        internal static string Gnome_Forest {
            get {
                return ResourceManager.GetString("Gnome:Forest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0_0_0_0_+2_0_25_Small_Common, Gnomish_None_Darkvision - 60ft, Gnome Cunning.
        /// </summary>
        internal static string Gnome_Natural {
            get {
                return ResourceManager.GetString("Gnome:Natural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0_0_+1_0_+2_0_25_Small_Common, Gnomish_None_Darkvision - 60ft, Gnome Cunning, Artificer&apos;s Lore, Tinker.
        /// </summary>
        internal static string Gnome_Rock {
            get {
                return ResourceManager.GetString("Gnome:Rock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0_0_0_0_0_+2_30_Medium_Common, Elvish_None_Darkvision - 60ft, Fey Ancestry, Skill Versatility.
        /// </summary>
        internal static string Half_Elf_Natural {
            get {
                return ResourceManager.GetString("Half-Elf:Natural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +2_0_+1_0_0_0_30_Medium_Common, Orc_Intimidation_Darkvision - 60ft, Relentless Endurance, Savage Attacks.
        /// </summary>
        internal static string Half_Orc_Natural {
            get {
                return ResourceManager.GetString("Half-Orc:Natural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0_+2_0_0_0_+1_25_Small_Common, Halfling_None_Lucky, Brave, Halfling Nimbleness, Naturally Stealthy.
        /// </summary>
        internal static string Halfling_Lightfoot {
            get {
                return ResourceManager.GetString("Halfling:Lightfoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0_+2_0_0_0_0_25_Small_Common, Halfling_None_Lucky, Brave, Halfling Nimbleness.
        /// </summary>
        internal static string Halfling_Natural {
            get {
                return ResourceManager.GetString("Halfling:Natural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0_+2_+1_0_0_0_25_Small_Common, Halfling_None_Lucky, Brave, Halfling Nimbleness, Stout Resilience.
        /// </summary>
        internal static string Halfling_Stout {
            get {
                return ResourceManager.GetString("Halfling:Stout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +1_+1_+1_+1_+1_+1_30_Medium_Common_None_None.
        /// </summary>
        internal static string Human_Natural {
            get {
                return ResourceManager.GetString("Human:Natural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0_0_0_0_0_0_30_Medium_Common_None_+1 to 2 stats, Choose a Feat.
        /// </summary>
        internal static string Human_Variant {
            get {
                return ResourceManager.GetString("Human:Variant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STR_DEX_CON_WIS_INT_CHA_SPEED_SIZE_LANGUAGE_PROFICINCY_BONUS.
        /// </summary>
        internal static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0_0_0_0_+1_+2_30_Medium_Common, Infernal_None_Darkvision - 60ft, Hellish Resistance, Infernal Legacy.
        /// </summary>
        internal static string Tiefling_Natural {
            get {
                return ResourceManager.GetString("Tiefling:Natural", resourceCulture);
            }
        }
    }
}
